#!/bin/sh

echo -ne '\033%G'

dbus-send --type=method_call --dest=me.wm / me.wm.none

xchainkeys -d >$HOME/.xchainkeys.log 2>&1 &

display -window root ~/pictures/Wallpaper-idea-swirl.png
# ( source $HOME/.fehbg )

xbindkeys

tint2 &

yong &

tomighty &

volume-control.lisp
