#!/bin/sh

echo -ne '\033%G'

xset r rate 250 20

wm-assist.py

xchainkeys -d >$HOME/.xchainkeys.log 2>&1 &

( source $HOME/.fehbg )

xbindkeys

tint2 &

dropbox.py start

scim -d

volume-control-alsa
